 INSERT INTO users(id, email, first_name, last_name, password, state) VALUES
 (1,
    'kyle@getyodlr.com',
    'Kyle',
    'White',
    '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
    'active'
    ),
  (2,
   'jane@getyodlr.com',
    'Jane',
    'Stone',
    '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
    'active'
  ),
  (3,
   'lilly@getyodlr.com',
    'Lilly',
    'Smith',
    '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
    'pending'
  ),
  (4,
   'fred@getyodlr.com',
    'Fred',
   'Miles',
   '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
   'pending'
  ),
  (5,
   'alex@getyodlr.com',
   'Alexandra',
    'Betts',
    '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
    'pending'
  );